package controller.servlets;

import javax.servlet.http.HttpServlet;

/**
 * @author Narwutsch Dominic
 * created on 08.03.2021
 */
public class ExperimentServlet extends HttpServlet {
    // Basisfelder
    public static final String NO_ID = "EXPERIMENT_NO_ID";
    public static final String API_STARTMATERIAL = "EXPERIMENT_API_STARTMATERIAL";
    public static final String SCREENING_NO = "EXPERIMENT_SCREENING_NO";
    public static final String PLANUNG_ERFOLGT_DURCH = "EXPERIMENT_PLANUNG_ERFOLGT_DURCH";
    public static final String EXPERIMENT_SERIE = "EXPERIMENT_EXPERIMENT_SERIE";
    public static final String EXPERIMENT_SERIE_TEXT = "EXPERIMENT_EXPERIMENT_SERIE_TEXT";
    public static final String EXPERIMENT_NO = "EXPERIMENT_EXPERIMENT_NO"; // Ist zwei mal da
    public static final String DURCHFUEHRUNGSTEXT = "EXPERIMENT_DURCHFUEHRUNGSTEXT";
    public static final String DURCHFUEHRUNGSTEXT_TEXT = "EXPERIMENT_DURCHFUEHRUNGSTEXT_TEXT";
    public static final String PROJEKTLEITERNOTIZ_INTENTION = "EXPERIMENT_PROJEKTLEITERNOTIZ_INTENTION";
    public static final String VERWEIS = "EXPERIMENT_VERWEIS";
    public static final String STARTFREIGABE = "EXPERIMENT_STARTFREIGABE";
    public static final String ERLEDIGT_BIS = "EXPERIMENT_ERLEDIGT_BIS";
    public static final String HINWEIS_AN_LABORLEITER = "EXPERIMENT_KINWEIS_AN_LABORLEITER";
    public static final String PLANUNG_ABGESCHLOSSEN = "EXPERIMENT_PLANUNG_ABGESCHLOSSEN";
    public static final String PRIORITAET_EXPERIMENT = "EXPERIMENT_PRIORITAET_EXPERIMENT";
    public static final String SICHERHEITSHINWEIS = "EXPERIMENT_SICHERHEITSHINWEIS";
    public static final String VERANTWORTLICHER_OPERATOR = "EXPERIMENT_VERANTWORTLICHER_OPERATOR";
    public static final String EXPERIMENT_START = "EXPERIMENT_EXPERIMENT_START"; // Ist zwei mal da
    public static final String API_STARTMATERIAL_SOLL_EINWAAGE = "EXPERIMENT_API_STARTMATERIAL_SOLL_EINWAAGE";
    public static final String API_STARTMATERIAL_SOLL_EINWAAGE_MG = "EXPERIMENT_API_STARTMATERIAL_SOLL_EINWAAGE_MG";
    public static final String COF_BEZEICHNUNG = "EXPERIMENT_COF_BEZEICHNUNG";
    public static final String COF_REF_CODE = "EXPERIMENT_COF_REF_CODE";
    public static final String COF_SOLL_EINWAAGE = "EXPERIMENT_COF_SOLL_EINWAAGE";
    public static final String COF_SOLL_EINWAAGE_MG = "EXPERIMENT_COF_SOLL_EINWAAGE_MG";
    public static final String SOLL_TEMPERATUR = "EXPERIMENT_SOLL_TEMPERATUR";
    public static final String LOESUNGSMITTEL_API_COF = "EXPERIMENT_LOESUNGSMITTEL_API_COF";
    public static final String LOESUNGSMITTEL_IN_VOLUMEN = "EXPERIMENT_LOESUNGSMITTEL_IN_VOLUMEN";
    public static final String BEOBACHTUNG_SLURRYERSTELLUNG_ODER_AENDERUNGEN_DES_EXPERIMENTS = "EXPERIMENT_BEOBACHTUNG_SLURRYERSTELLUNG_ODER_AENDERUNGEN_DES_EXPERIMENTS";
    public static final String BEOBACHTUNGEN_EXPERIMENTVERLAUF = "EXPERIMENT_BEOBACHTUNGEN_EXPERIMENTVERLAUF";
    public static final String EXPERIMENT_ENDE = "EXPERIMENT_EXPERIMENT_ENDE";
    public static final String STATUS_EXPERIMENT = "EXPERIMENT_STATUS_EXPERIMENT";
    public static final String AUFBEREITUNG_PRAESENTATION_PXRD = "EXPERIMENT_AUFBEREITUNG_PRAESENTATION_PXRD";
    public static final String BEOBACHTUNGEN_ENDE_EXPERIMENT_UND_AUFBEREITUNG = "EXPERIMENT_BEOBACHTUNGEN_ENDE_EXPERIMENT_UND_AUFBEREITUNG";
    public static final String STANDORT_LAGERORT_FINALE_PROBE = "EXPERIMENT_STANDORT_LAGERORT_FINALE_PROBE";
    public static final String PRIORITAET_ANALYSTIK = "EXPERIMENT_PRIORITAET_ANALYSTIK";
    public static final String ERSTANALYSTIK_PXRD = "EXPERIMENT_ERSTANALYSTIK_PXRD";
    public static final String PXRD_MOEGLICH = "EXPERIMENT_PXRD_MOEGLICH";
    public static final String AUSBEUTE_REST_WEITERE_ANALYSTIK_MOEGLICH = "EXPERIMENT_AUSBEUTE_REST_WEITERE_ANALYSTIK_MOEGLICH";
    public static final String ERGEBNIS_PXRD = "EXPERIMENT_ERGEBNIS_PXRD";
    public static final String FOLGEANALYTIK_DSC = "EXPERIMENT_FOLGEANALYTIK_DSC";
    public static final String FOLGEANALYTIK_TG = "EXPERIMENT_FOLGEANALYTIK_TG";
    public static final String FOLGEANALYTK_PXRD_II = "EXPERINENT_FOLGEANALYTK_PXRD_II";
    public static final String FOLGEANALYTIK_H_NMR = "EXPERIMENT_FOLGEANALYTIK_H_NMR";
    public static final String FOLGEANALYTIK_IR = "EXPERIMENT_FOLGEANALYTIK_IR";
    public static final String FOLGEANALYTIK_RAMAN = "EXPERIMENT_FOLGEANALYTIK_RAMAN";
    public static final String FOLGEANALYTIK_OMI = "EXPERIMENT_FOLGEANALYTIK_OMI";
    public static final String INFORMATIONEN_FOLGEANALYSTIK = "EXPERIMENT_INFORMATIONEN_FOLGEANALYSTIK";
    public static final String ERGEBNIS_DSC = "EXPERIMENT_ERGEBNIS_DSC";
    public static final String ERGEBNIS_TG = "EXPERIMENT_ERGEBNIS_TG";
    public static final String ERGEBNIS_PXRD_II = "EXPERIMENT_ERGEBNIS_PXRD_II";
    public static final String ERGEBNIS_H_NMR = "EXPERIMENT_ERGEBNIS_H_NMR";
    public static final String ERGEBNIS_IR = "EXPERIMENT_ERGEBNIS_IR";
    public static final String ERGEBNIS_RAMAN = "EXPERIMENT_ERGEBNIS_RAMAN";
    public static final String ERGEBNIS_OMI = "EXPERIMENT_ERGEBNIS_OMI";
    public static final String STATUS_ANALYSTIK = "EXPERIMENT_STATUS_ANALYSTIK";
    public static final String GESAMT_ERGEBNIS = "EXPERIMENT_GESAMT_ERGEBNIS";
    public static final String EINSTUFUNG_ERGEBNIS = "EXPERIMENT_EINSTUFUNG_ERGEBNIS";
    public static final String TYP = "EXPERIMENT_TYP";
    public static final String VORGABE_INFO_VOLUMEN = "EXPERIMENT_VORGABE_INFO_VOLUMEN";

    // Verdampfung
    public static final String VIAL_TARA_G = "EXPERIMENT_VIAL_TARA_G";
    public static final String AUSBEUTE_VIAL_KRISTALLAT_G = "EXPERIMENT_AUSBEUTE_VIAL_KRISTALLAT_G";
    public static final String AUSBEUTE_MG_PRAEP_ANALYTIK = "EXPERIMENT_AUSBEUTE_MG_PRAEP_ANALYTIK";
}
