
const EventType = {};

EventType.PARTNER = {
    AUSWAEHLEN : "PARTNER.AUSWAEHLEN",
    ERSTELLEN : "PARTNER.ERSTELLEN",
    BEARBEITEN : "PARTNER.BEARBEITEN",
    GESPEICHERT : "PARTNER.GESPEICHERT",
};

EventType.PROJEKT = {
    AUSWAEHLEN : "PROJEKT.AUSWAEHLEN",
    ERSTELLEN : "PROJEKT.ERSTELLEN",
    BEARBEITEN : "PROJEKT.BEARBEITEN",
    GESPEICHERT : "PROJEKT.GESPEICHERT",
};

EventType.STATE = {
    PARTNER : "STATE.PARTNER",
}

export default EventType;