
const Events = {};

Events.PARTNER = {
    AUSWAEHLEN : "PARTNER.AUSWAEHLEN",
    ERSTELLEN : "PARTNER.ERSTELLEN",
    BEARBEITEN : "PARTNER.BEARBEITEN",
};

Events.PROJEKT = {
    AUSWAEHLEN : "PROJEKT.AUSWAEHLEN",
    ERSTELLEN : "PROJEKT.ERSTELLEN",
    BEARBEITEN : "PROJEKT.BEARBEITEN",
};


export default Events;