
const EventType = {};

EventType.PARTNER = {
    AUSWAEHLEN : "PARTNER.AUSWAEHLEN",
    ERSTELLEN : "PARTNER.ERSTELLEN",
    BEARBEITEN : "PARTNER.BEARBEITEN",
    GESPEICHERT : "PARTNER.GESPEICHERT",
    SUCHEN : "PARTNER.SUCHEN",
};

EventType.PROJEKT = {
    AUSWAEHLEN : "PROJEKT.AUSWAEHLEN",
    ERSTELLEN : "PROJEKT.ERSTELLEN",
    BEARBEITEN : "PROJEKT.BEARBEITEN",
    GESPEICHERT : "PROJEKT.GESPEICHERT",
    SUCHEN : "PROJEKT.SUCHEN",
};

EventType.PROBE = {
    AUSWAEHLEN : "PROBE.AUSWAEHLEN",
    EINGANG : "PROBE.EINGANG",
    BEARBEITEN : "PROBE.BEARBEITEN",
    GESPEICHERT : "PROBE.GESPEICHERT",
    SUCHEN : "PROBE.SUCHEN",
};

EventType.EXPERIMENT = {
    ERSTELLEN : "EXPERIMENT.ERSTELLEN",
    AUSWAEHLEN : "EXPERIMENT.AUSWAEHLEN",
    BEARBEITEN : "EXPERIMENT.BEARBEITEN",
    GESPEICHERT : "EXPERIMENT.GESPEICHERT",
    SUCHEN : "EXPERIMENT.SUCHEN",
};

EventType.ANALYSE = {
    ERSTELLEN : "ANALYSE.ERSTELLEN",
    AUSWAEHLEN : "ANALYSE.AUSWAEHLEN",
    BEARBEITEN : "ANALYSE.BEARBEITEN",
    GESPEICHERT : "ANALYSE.GESPEICHERT",
    SUCHEN : "ANALYSE.SUCHEN",
    EINGANGSANALYSE : "ANALYSE.EINGANGSANALYSE",
};

EventType.SUCHE = {
    AUFRUFEN : "SUCHE.AUFRUFEN",
    SCHLIESSEN : "SUCHE.SCHLIESSEN",
    MINIMIEREN : "SUCHE.MINIMIEREN",
}

EventType.EXPLORER = {
    AUFRUFEN : "EXPLORER.AUFRUFEN",
    SCHLIESSEN : "EXPLORER.SCHLIESSEN",
    MINIMIEREN : "EXPLORER.MINIMIEREN",
    PARTNER_LIST : "EXPLORER.PARTNER_LIST",
    PARTNER : "EXPLORER.PARTNER",
    PROBE : "EXPLORER.PROBE",
    EXPERIMENT : "EXPLORER.EXPERIMENT",
    ANALYSE : "EXPLORER.ANALYSE",
}

EventType.STATE = {
    PARTNER : "STATE.PARTNER",
    PROJEKT : "STATE.PROJEKT",
    EXPERIMENT : "STATE.EXPERIMENT",
    ANALYSE : "STATE.ANALYSE",
    PROBE : "STATE.PROBE",
}

export default EventType;